-- this file is autogenerated by WowUp (app) at Wed Aug 03 2022 21:52:22 GMT+0200 (Midden-Europese zomertijd)
WOWUP_DATA = {}
WOWUP_DATA.icon = "Interface/AddOns/wowup_data_addon/ldbicon"
WOWUP_DATA.addonManagerName = "WowUp"
WOWUP_DATA.addonManagerColorRGB = {232/255,205/255,134/255}
WOWUP_DATA.addonManagerNameSlashCommand = "/wowup"
WOWUP_DATA.updateAddonsList = {
}
